name: PyPI

on:
  push:
    branches: [ Fal-Userbot ]
  pull_request:
    branches: [ Fal-Userbot ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up PyPI
      uses: actions/setup-PyPI@v3
      with:
        PyPI-version: 3.9

  - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: falprojects/fal-userbot:busterv1
